# Generated by Django 4.2.1 on 2023-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcaptain', '0003_paymentcategory_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
