# Generated by Django 4.2.1 on 2023-05-30 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subcaptain', '0004_alter_paymentcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcategory',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='recurringpayment',
            unique_together={('name', 'owner')},
        ),
    ]
