# Generated by Django 4.2.1 on 2023-05-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcaptain', '0005_alter_paymentcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentcategory',
            unique_together=set(),
        ),
    ]
